include nero.conf

# Font
font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font
italic_font      auto
bold_italic_font auto
font_size        12

# Cursor
cursor_shape     block
cursor_interval  500

# Window
background_opacity 0.8
confirm_os_window_close 0

# Scrolling
scrollback_lines 10000

# Mouse (negative = hide immediately when typing)
mouse_hide_wait  -1.0

# Selection
copy_on_select yes

# Terminal
term xterm-256color

# URL handling
url_color        #a9c7d6
url_style        dotted


