## name:     Nero
## blurb:    Dark navy theme, ported from Alacritty Nero

foreground              #a9c7d6
background              #0d1c2e

# Selection colors
selection_foreground    #0d1c2e
selection_background    #a9c7d6

# Cursor colors
cursor                  #a9c7d6
cursor_text_color       #0d1c2e

# Black
color0  #0A1522
color8  #132842

# Red
color1  #f5596b
color9  #f5596b

# Green
color2  #92cc33
color10 #92cc33

# Yellow
color3  #e0a352
color11 #e0a352

# Blue
color4  #0da8f2
color12 #0da8f2

# Magenta
color5  #b291f3
color13 #b291f3

# Cyan
color6  #3df5de
color14 #3df5de

# White
color7  #a9c7d6
color15 #a9c7d6

# Indexed colors (from Alacritty Nero)
color16 #ff9e64
color17 #db4b4b
